# Generated by Django 3.0.2 on 2020-02-02 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200122_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 8, 39, 9, 199797, tzinfo=utc)),
        ),
    ]
