# Generated by Django 3.0.2 on 2020-02-06 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200202_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 9, 23, 36, 762992, tzinfo=utc)),
        ),
    ]
