# Generated by Django 3.0.2 on 2020-02-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200218_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=True, upload_to='', verbose_name=object),
            preserve_default=False,
        ),
    ]
