# Generated by Django 3.0.3 on 2020-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200403_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programing_languages',
            field=models.TextField(default='HTML', verbose_name=['HTML', 'CSS', 'JavaScript', 'Bootstrap', 'Jquery', 'Python']),
        ),
    ]
