# Generated by Django 3.0.3 on 2020-04-04 10:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_programing_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='programing_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Bootstrap', 'Bootstrap'), ('jQuery', 'jQuery'), ('Python', 'Python')], max_length=43),
        ),
    ]
